# Autenticação KDE (kwallet, sudo GUI)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Portais XDG
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = systemctl --user start xdg-desktop-portal-kde

# Notificações
exec-once = swaync

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


exec-once = waybar

# Wallpaper
exec-once = hyprpaper


# Tema GTK via gsettings
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Breeze-Dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'breeze-dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
