# Autenticação KDE (kwallet, sudo GUI)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Portais XDG
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = systemctl --user start xdg-desktop-portal-kde


# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


# Tema GTK via gsettings
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Breeze-Dark'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'breeze-dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

#Init Apps
exec-once = waybar & swaync & hypridle
exec-once = awww-daemon && awww img /home/jefferson/.config/backgrounds/hyprgirl.png
