# --- Autostart Refatorado (Pure Hyprland) ---

# 1. Portais e D-Bus (Obrigatório para NVIDIA e Apps demorarem menos a abrir)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# 2. Polkit (Autenticação sudo em interface)
# Instale o hyprpolkitagent: sudo pacman -S hyprpolkitagent
exec-once = hyprpolkitagent

# 3. Mouse e Temas (Garante que o XWayland/Steam vejam o cursor)
exec-once = hyprctl setcursor capitaine-cursors 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "catppuccin-mocha-sapphire-standard+default"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
# 4. Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# 5. Apps de Sistema
exec-once = waybar & swaync & hypridle
exec-once = awww-daemon && awww img /home/jefferson/.config/backgrounds/hyprgirl.png
exec-once = nm-applet --indicator
