# Cursor — herdado do KDE
env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,capitaine-cursors
env = HYPRCURSOR_SIZE,24

# Qt — Breeze como no KDE
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,Breeze-Dark
env = QT_QPA_PLATFORMTHEME,kde
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# GTK — Breeze Dark
env = GTK_THEME,Breeze-Dark
env = GDK_BACKEND,wayland,x11

# NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm



# Wayland geral
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_SESSION_DESKTOP,wayland
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto
