# -----------------------------------------------------
# CONFIGURAÇÃO DO TECLADO INTEGRADO (Notebook Alienware)
# -----------------------------------------------------
input {
    kb_layout = br
    kb_variant = 
    kb_model = 
    
    # ESTE É O SEGREDO PARA O NOTEBOOK:
    # Inverte o Alt Esquerdo com o Control Esquerdo fisicamente.
    # O Alt (do lado do espaço) vira o seu "Command" (Control).
    kb_options = ctrl:swap_lalt_lctrl
    
    kb_rules =
    follow_mouse = 1
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

# -----------------------------------------------------
# CONFIGURAÇÃO PARA O MX KEYS S (Via Keyd Virtual)
# -----------------------------------------------------
device {
    # Nome padrão que o keyd cria
    name = keyd-virtual-keyboard
    
    # Define o layout como americano
    kb_layout = us
    
    # IMPORTANTE: Use a variante 'intl' para conseguir fazer o "ç" 
    # e acentos (usando ' + c ou a tecla AltGr da direita)
    kb_variant = mac
    
    # Deixamos vazio porque o 'keyd' já fez a inversão das teclas 
    # no nível do hardware antes de chegar aqui!
    kb_options = 
}
