input {
    kb_layout = br
    kb_variant = abnt2
    kb_options = altwin:swap_lalt_lwin
    
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

device {
    name = mx-keys-s-keyboard
    kb_layout = us
    kb_variant = altgr-intl,cedilla # Adicionamos a variante cedilla aqui
    kb_model = logitech_base
    kb_options = altwin:swap_lalt_lwin,lv3:ralt_switch
}
