# -----------------------------------------------------
# CONFIGURAÇÃO DO TECLADO INTEGRADO (Notebook Alienware)
# -----------------------------------------------------
input {
    kb_layout = br
    kb_variant = 
    kb_model = 
    
    # ESTE É O SEGREDO PARA O NOTEBOOK:
    # Inverte o Alt Esquerdo com o Control Esquerdo fisicamente.
    # O Alt (do lado do espaço) vira o seu "Command" (Control).
   
    
    kb_rules =
    follow_mouse = 1
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

# -----------------------------------------------------
# CONFIGURAÇÃO PARA O MX KEYS S (Via Keyd Virtual)
# -----------------------------------------------------
device {
    name = mx-mchncl-m-keyboard
    kb_layout = us
    kb_variant = intl
    kb_model = 
    
       
   }
