source = ~/.config/hypr/modules/catppuccin-hyprland/themes/mocha.conf

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    
    # Aplica o Mauve e o Blue do Catppuccin
    col.active_border = $mauve $blue 45deg
    col.inactive_border = $crust

    layout = dwindle # ou master, dependendo da sua preferência
}

decoration {
    rounding = 6
    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = true
        range = 8
        render_power = 3
        color = rgba(0a0a0acc)
    }

    blur {
        enabled = true
        size = 4
        passes = 2
        vibrancy = 0.15
    }
}

animations {
    enabled = yes

    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = quick, 0.15, 0, 0.1, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1

    animation = windows,      1, 4,   easeOutQuint
    animation = windowsIn,    1, 4,   easeOutQuint, popin 87%
    animation = windowsOut,   1, 2,   quick,        popin 87%
    animation = border,       1, 5,   easeOutQuint
    animation = fade,         1, 3,   quick
    animation = workspaces,   1, 2,   almostLinear, fade
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}


