# DP-1 — Odyssey G5 esquerda
monitor = DP-3, 2560x1440@165, 0x0, 1

# DP-3 — Odyssey G5 centro
monitor = DP-1, 2560x1440@165,2560x0, 1

# eDP-1 — Notebook direita (125% = scale 1.25)
monitor = eDP-1, 2560x1600@120,5120x0, 1.25

# Workspaces
workspace = 1, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 5, monitor:DP-3
workspace = 7, monitor:DP-3
workspace = 9, monitor:DP-3

workspace = 2, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 8, monitor:DP-1
