# /etc/keyd/default.conf

[ids]
# Intercepta APENAS o Logitech MX Keys S, ignorando o notebook
046d:b378

[main]
# Faz a tecla Command/Alt física esquerda enviar o sinal de Control
leftalt = leftcontrol

# (Opcional) A tecla Control física esquerda passa a agir como Alt
leftcontrol = leftalt

# ---------------------------------------------------------
# ONE-SHOT MODIFIERS (Switches de 1 toque)
# ---------------------------------------------------------
leftshift = oneshot(shift)
rightshift = oneshot(shift)
rightalt = oneshot(altgr)
