source = ~/.config/hypr/modules/catppuccin-hyprland/themes/mocha.conf

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.6
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $sapphire
    font_size = 90
    font_family = CaskaydiaCove Nerd Font
    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(LC_TIME=en_US.UTF-8 date +'%A, %d %B %Y')"
    color = $text
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR
image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $sapphire
    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $sapphire
    inner_color = $mantle
    font_color = $text
    fade_on_empty = false
    # O Pango (span) no Hyprlock aceita as cores diretamente em Hex. 
    # Usei o hex do Mocha Text (cdd6f4) e do Mocha Sapphire (74c7ec).
    placeholder_text = <span foreground="##cdd6f4"><i>󰌾 Logged in as </i><span foreground="##74c7ec">$USER</span></span>
    hide_input = false
    check_color = $sapphire
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $peach
    position = 0, -35
    halign = center
    valign = center
}
