# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.6
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = rgba(efeff1ff)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(LC_TIME=en_US.UTF-8 date +'%A, %d %B %Y')"
    color = rgba(bdc3c7ff)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR
image {
    monitor =
    path = ~/.face
    size = 100
    border_color = rgba(3daee9ff)
    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(3daee9ff)
    inner_color = rgba(35383bff)
    font_color = rgba(efeff1ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##eff0f1"><i>󰌾 Logged in as </i><span foreground="##3daee9">$USER</span></span>
    hide_input = false
    check_color = rgba(3daee9ff)
    fail_color = rgba(da4453ff)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgba(f67400ff)
    position = 0, -35
    halign = center
    valign = center
}
