preload = /home/jefferson/.config/backgrounds/hyprgirl.png
wallpaper = DP-1,/home/jefferson/.config/backgrounds/hyprgirl.png
wallpaper = DP-3,/home/jefferson/.config/backgrounds/hyprgirl.png
wallpaper = eDP-1,/home/jefferson/.config/backgrounds/hyprgirl.png
