# --- Fonte ---
font_family      CaskaydiaMono Nerd Font
bold_font        CaskaydiaMono Nerd Font Bold
italic_font      CaskaydiaMono Nerd Font Italic
bold_italic_font CaskaydiaMono Nerd Font Bold Italic
font_size        16.0

# --- Transparência ---
background_opacity 0.85
background_blur 32

# --- Janela ---
window_padding_width 5
hide_window_decorations yes

# --- Cursor ---
cursor_shape beam
cursor_blink_interval 0.5

# --- Scroll ---
scrollback_lines 10000

# --- Tema ---
include themes/catppuccin/themes/Catppuccin-Mocha.conf
